// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteResource(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DeleteResource'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function EditResource(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['EditResource'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExecPod(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecPod'](arg1, arg2, arg3);
}

export function GetApiResources() {
  return window['go']['main']['App']['GetApiResources']();
}

export function GetCurrentContext() {
  return window['go']['main']['App']['GetCurrentContext']();
}

export function GetKubeContexts() {
  return window['go']['main']['App']['GetKubeContexts']();
}

export function GetNamespaces() {
  return window['go']['main']['App']['GetNamespaces']();
}

export function GetPodLogs(arg1) {
  return window['go']['main']['App']['GetPodLogs'](arg1);
}

export function GetRelatedResources(arg1) {
  return window['go']['main']['App']['GetRelatedResources'](arg1);
}

export function GetResource(arg1) {
  return window['go']['main']['App']['GetResource'](arg1);
}

export function InitDefaultContext() {
  return window['go']['main']['App']['InitDefaultContext']();
}

export function ListResources(arg1) {
  return window['go']['main']['App']['ListResources'](arg1);
}

export function SetActiveContext(arg1) {
  return window['go']['main']['App']['SetActiveContext'](arg1);
}
