// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {k8s} from '../models';
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteResource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function EditResource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function ExecPod(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetApiResources():Promise<Array<k8s.ApiResourceInfo>>;

export function GetCurrentContext():Promise<string>;

export function GetKubeContexts():Promise<Array<k8s.KubeContext>>;

export function GetNamespaces():Promise<Array<string>>;

export function GetPodLogs(arg1:main.LogsParams):Promise<string>;

export function GetRelatedResources(arg1:main.RelatedParams):Promise<Array<any>>;

export function GetResource(arg1:main.GetParams):Promise<any>;

export function InitDefaultContext():Promise<string>;

export function ListResources(arg1:main.ListParams):Promise<Array<any>>;

export function SetActiveContext(arg1:string):Promise<void>;
